services:
  postgres:
    env_file:
      - .env
    image: postgres:17-bookworm
    container_name: flowerplus_postgres17
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-thang}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-flowerplus_db}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - flowerplus_postgres_data:/var/lib/postgresql/data
      # Dòng dưới này OK, nhưng nhớ là nó chỉ chạy script khi DB trắng trơn lần đầu thôi nhé
      #- ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-flowerplus_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    env_file:
      - .env
    image: rabbitmq:4.2.2-management-alpine # Bản management có giao diện Web Admin
    container_name: rabbitmq_flowerplus
    restart: no
    ports:
      - "5672:5672"   # Port để code Java kết nối
      - "15672:15672" # Port để vào trang Admin Web


  redis:
    image: redis:7-alpine
    container_name: flowerplus_redis
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      # ĐÃ SỬA: Phải khớp với tên khai báo ở cuối file
      - flowerplus_redis_data:/data
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  maildev:
    image: maildev/maildev
    container_name: flowerplus_maildev
    restart: always
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP Port

volumes:
  flowerplus_postgres_data:
  flowerplus_redis_data: # Khớp với service redis ở trên rồi

# Đã xóa phần networks cho gọn