server:
  port: 80
  tomcat:
    max-http-form-post-size: 10MB
    max-swallow-size: 10MB

spring:
  application:
    name: flowerplus
  profiles:
    active: '@spring.profiles.active@'
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


