app:
  base-url: http://localhost:8080
  frontend-url: http://localhost:3000
  db-seeder: true
  name: FLOWERPLUS
  tagline: Flower Shop
  url: https://flowerplus.io.vn



jwt:
  key:
    id: "flowerplus-key-2025"
    private-path: classpath:certs/private_key.pem
    public-path: classpath:certs/public_key.pem
  refresh:
    expiration: 2592000000 # 30 days in milliseconds

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}

spring:
  config:
    activate:
      on-profile: dev

  jackson:
    time-zone: UTC
    default-property-inclusion: non_null

  web:
    resources:
      add-mappings: false

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/flowerplus_db?stringtype=unspecified}
    username: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:thang}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:123456}}
    driver-class-name: org.postgresql.Driver

  flyway:
    enabled: true
    user: ${SPRING_DATASOURCE_USERNAME:${POSTGRES_USER:thang}}
    password: ${SPRING_DATASOURCE_PASSWORD:${POSTGRES_PASSWORD:123456}}
    # Automatically create flyway_schema_history table if it doesn't exist
    baseline-on-migrate: true
    # Set baseline version to 0 (to avoid errors if DB already has data)
    baseline-version: 0
    # Directory containing sql files (default is db/migration)
    locations: classpath:db/migration
    # (Optional for Dev) Allow Flyway to validate checksum.
    # If you modify old migration files, Flyway will report error. Set false if you often modify old files (not recommended).
    validate-on-migrate: true
    # (Optional) Default schema, usually public for Postgres
    default-schema: public

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

    show_sql: false
    hibernate:
      ddl-auto: none

  mail:
    host: localhost
    port: 1025
    username: "noreply@flowerplus.com"
    password: ""
    properties:
      mail.smtp.auth: false
      mail.smtp.starttls.enable: false

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      repositories:
        enabled: false
      url: ${REDIS_URL:}


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid, profile, email
            redirect-uri: http://localhost:3000/auth/google-callback
            authorization-grant-type: authorization_code
            client-name: Google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v2/userinfo
            user-name-attribute: sub



open:
  api:
    serverUrl: https://api.flowerplus.io.vn
    title: Flower Plus  API (Dev)
    version: v1.0.0
    serverName: Flower Plus Backend API
    description: API documentation for Flower Plus shop ecommerce project.

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    root: INFO
    com.greenwich.flowerplus: DEBUG  # Print detailed code logs
    #org.hibernate.SQL: DEBUG   # Print SQL statements to console for convenience

# Swagger (springdoc-openapi)
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

server:
  port: 8080